### ISSUE TITLE
pkg: Missing dependency 'mbedtls'

### ISSUE THREAD

**Issue by toca-cals** [MediaBrowser/iocage-amd64#7]
git clone https://github.com/MediaBrowser/iocage-amd64.git
cd iocage-amd64
iocage fetch -P emby-server.json dhcp="on" ip6="inherit" allow_mlock="on" --branch master

Plugin: emby-server
  Official Plugin: False
  Using RELEASE: 13.1-RELEASE
  Using Branch: master
  Post-install Artifact: https://github.com/MediaBrowser/iocage-amd64.git
  These pkgs will be installed:
    - audio/libogg
    - audio/libvorbis
    - audio/opus
    - converters/fribidi
    - databases/sqlite3
    - devel/icu
    - devel/libinotify
    - devel/libunwind
    - devel/orc
    - converters/fribidi
    - converters/libiconv
    - devel/libzvbi
    - devel/ocl-icd
    - graphics/jpeg-turbo
    - graphics/libdrm
    - graphics/libexif
    - graphics/libheif
    - graphics/libimagequant
    - graphics/libjxl
    - graphics/openexr
    - graphics/openjpeg
    - graphics/png
    - graphics/tesseract
    - graphics/tiff
    - graphics/webp
    - multimedia/intel-media-sdk
    - multimedia/libass
    - multimedia/libtheora
    - multimedia/libva
    - print/freetype2
    - security/gnutls
    - security/krb5
    - security/openssl
    - textproc/expat2
    - x11-fonts/fontconfig
    - x11-toolkits/pango

Testing Host DNS response to pkg.freebsd.org
Testing emby-server's SRV response to pkg.freebsd.org
Testing emby-server's DNSSEC response to pkg.freebsd.org

Installing plugin packages:
  - audio/libogg... 
  - audio/libvorbis... 
  - audio/opus... 
  - converters/fribidi... 
  - databases/sqlite3... 
  - devel/icu... 
  - devel/libinotify... 
  - devel/libunwind... 
  - devel/orc... 
  - converters/fribidi... 
  - converters/libiconv... 
  - devel/libzvbi... 
  - devel/ocl-icd... 
  - graphics/jpeg-turbo... 
  - graphics/libdrm... 
  - graphics/libexif... 
  - graphics/libheif... 
  - graphics/libimagequant... 
  - graphics/libjxl... 
  - graphics/openexr... 
  - graphics/openjpeg... 
  - graphics/png... 
  - graphics/tesseract... 
  - graphics/tiff... 
  - graphics/webp... 
  - multimedia/intel-media-sdk... 
  - multimedia/libass... 
  - multimedia/libtheora... 
  - multimedia/libva... 
  - print/freetype2... 
  - security/gnutls... 
  - security/krb5... 
  - security/openssl... 
  - textproc/expat2... 
  - x11-fonts/fontconfig... 
  - x11-toolkits/pango... 

Fetching artifact... 
Cloning git repository

Running post_install.sh
[emby-server] Fetching emby-server-freebsd13_4.7.13.0_amd64.pkg: .......... done
[emby-server] Installing emby-server-4.7.13.0_1...
[emby-server] Installing emby-server-4.7.13.0_1...
pkg: Missing dependency 'mbedtls'

Failed to install the following 1 package(s): https://github.com/MediaBrowser/Emby.Releases/releases/download/4.7.13.0/emby-server-freebsd13_4.7.13.0_amd64.pkg
pkg: Missing dependency 'mbedtls'
emby_server_enable:  -> YES
pkg: Missing dependency 'mbedtls'
emby-server does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
pkg: Missing dependency 'mbedtls'
Last 10 lines:
pkg: Missing dependency 'mbedtls'
emby-server had a failure
Exception: SystemExit Message: 1
Partial plugin destroyed

============
FreeBSD hostname 13.1-RELEASE-p7 FreeBSD 13.1-RELEASE-p7 n245428-4dfb91682c1 TRUENAS amd64

**Comment by LukePulverenti** [comment]
HI, yes please follow along here: https://emby.media/community/index.php?/topic/116352-help-with-properly-installing-emby-on-truenas-core-131/#comment-1269482 

Thanks !
